/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

/**
 *
 * @author Cassandra
 */
public class VtnAlumnos extends javax.swing.JFrame
{

    /**
     * Creates new form VtnPrin
     */
    public VtnAlumnos()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RegistroHC = new javax.swing.JButton();
        ModificaAluProf = new javax.swing.JButton();
        ConsultaAluProf = new javax.swing.JButton();
        RegistroAluProf = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();
        ConsultaHA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de Alumnos");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Registro-HC.png"))); // NOI18N
        RegistroHC.setToolTipText("Registro de historial clinico");
        RegistroHC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegistroHCActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        ModificaAluProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/ModificacionAlumnos.png"))); // NOI18N
        ModificaAluProf.setToolTipText("Modificaciones de alumnos o profesores");
        ModificaAluProf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificaAluProfActionPerformed(evt);
            }
        });
        jPanel1.add(ModificaAluProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        ConsultaAluProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/ConsultaAlumnos.png"))); // NOI18N
        ConsultaAluProf.setToolTipText("Consulta de alumnos o profesores");
        ConsultaAluProf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConsultaAluProfActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultaAluProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        RegistroAluProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/RegistroAlumnos.png"))); // NOI18N
        RegistroAluProf.setToolTipText("Registro de alumnos o profesores");
        RegistroAluProf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegistroAluProfActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroAluProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Reportes.png"))); // NOI18N
        Reportes.setToolTipText("Reportes");
        Reportes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ReportesActionPerformed(evt);
            }
        });
        jPanel1.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        ConsultaHA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/busqueda-de-datos.png"))); // NOI18N
        ConsultaHA.setToolTipText("Consulta de alumnos o profesores");
        ConsultaHA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConsultaHAActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultaHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 210, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Inicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroAluProfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistroAluProfActionPerformed
    {//GEN-HEADEREND:event_RegistroAluProfActionPerformed
        new VtnRegistroAlu().setVisible(true);
    }//GEN-LAST:event_RegistroAluProfActionPerformed

    private void ConsultaAluProfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConsultaAluProfActionPerformed
    {//GEN-HEADEREND:event_ConsultaAluProfActionPerformed
        new VtnConsultaAlum().setVisible(true);
    }//GEN-LAST:event_ConsultaAluProfActionPerformed

    private void ModificaAluProfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificaAluProfActionPerformed
    {//GEN-HEADEREND:event_ModificaAluProfActionPerformed
        new buscaCveMA().setVisible(true);
    }//GEN-LAST:event_ModificaAluProfActionPerformed

    private void RegistroHCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistroHCActionPerformed
    {//GEN-HEADEREND:event_RegistroHCActionPerformed
        new buscaCveRHA().setVisible(true);
    }//GEN-LAST:event_RegistroHCActionPerformed

    private void ConsultaHAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConsultaHAActionPerformed
    {//GEN-HEADEREND:event_ConsultaHAActionPerformed
        //new buscaCveHA().setVisible(true);
        new VtnConsultaHA().setVisible(true);
    }//GEN-LAST:event_ConsultaHAActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ReportesActionPerformed
    {//GEN-HEADEREND:event_ReportesActionPerformed
        new VtnReportesA().setVisible(true);
    }//GEN-LAST:event_ReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaAluProf;
    private javax.swing.JButton ConsultaHA;
    private javax.swing.JButton ModificaAluProf;
    private javax.swing.JButton RegistroAluProf;
    private javax.swing.JButton RegistroHC;
    private javax.swing.JButton Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
