package vtngestor;

import cjb.ci.Mensaje;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectosp.Alumnos;
import proyectosp.HistorialClinico;
import proyectosp.Manipulacion;
import proyectosp.Personal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Cassandra
 */
public class VtnConsultaHA extends javax.swing.JFrame
{

    DefaultTableModel dtm;

    /**
     * Creates new form VtnConsultaH
     */
    public VtnConsultaHA()
    {
        initComponents();
        String com[] =
        {
                "Nombre", "Primer Apellido", "Segundo Apellido", "Padecimiento", "Antecedentes", "Medicamento", "Tratamiento", "Fecha"
        };
        dtm = new DefaultTableModel(com, 0);
        desp.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Historial Clinico Alumnos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        desp.setEnabled(false);
        jScrollPane1.setViewportView(desp);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1180, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/cve222.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) desp.getModel();
        model.setColumnIdentifiers(new Object[]
        {
            "Nombre", "Primer Apellido", "Segundo Apellido", "Padecimiento", "Antecedentes", "Medicamento", "Tratamiento", "Fecha"
        });

        JTableHeader header = desp.getTableHeader();
        header.setReorderingAllowed(false);

        JTableHeader header1 = desp.getTableHeader();
        header.setResizingAllowed(false);
        try
        {
            DefaultTableModel dtm = (DefaultTableModel) desp.getModel();
            String cvePaciente = JOptionPane.showInputDialog("Ingrese la clave del paciente:");
            int index = Manipulacion.buscarcve(VtnInicio.d, cvePaciente);

            if (index != -1 && VtnInicio.d[index] instanceof Alumnos)
            {
                // Mostrar las consultas del paciente
                for (int j = 0; j < VtnInicio.matriz[index].length; j++)
                {
                    HistorialClinico consulta = VtnInicio.matriz[index][j];
                    Object[] rowData =
                    {
                        VtnInicio.d[index].getNom(),
                        VtnInicio.d[index].getPrimerAp(),
                        VtnInicio.d[index].getSegundoAp(),
                        consulta.getPadecimientoAct(),
                        consulta.getAntededentesPer(),
                        consulta.getMedicamento(),
                        consulta.getPlanTratamiento(),
                        consulta.getFecha()
                    };
                    dtm.addRow(rowData);
                }
            } else
            {
                Mensaje.error(this, "No se encontró el paciente con clave " + cvePaciente);
            }
        } catch (Exception e)
        {
            Mensaje.error(this, "El CVE ingresado no cuenta con consultas registradas");
        }
    }//GEN-LAST:event_formWindowOpened

/**
 * @param args the command line arguments
 */
public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaHA.class 


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaHA.class 


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaHA.class 


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaHA.class 


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnConsultaHA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable desp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
