/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

import poo.ManipulacionArchivos13;
import proyectosp.Datos;
import proyectosp.HistorialClinico;

/**
 *
 * @author Cassandra
 */
public class VtnInicio extends javax.swing.JFrame
{
    public static Datos []d = null;
    public static HistorialClinico[][] matriz = null;
    /**
     * Creates new form VtnInicio
     */
    public VtnInicio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        alumnos = new javax.swing.JButton();
        personal = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlum = new javax.swing.JMenu();
        mnuRegAlum = new javax.swing.JMenuItem();
        mnuModAlum = new javax.swing.JMenuItem();
        HisAlum = new javax.swing.JMenuItem();
        mnuPer = new javax.swing.JMenu();
        mnuRegPer = new javax.swing.JMenuItem();
        mnuModPer = new javax.swing.JMenuItem();
        mnuHisPer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/companeros-de-clase.png"))); // NOI18N
        alumnos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                alumnosActionPerformed(evt);
            }
        });
        jPanel1.add(alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 240));

        personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/empleados.png"))); // NOI18N
        personal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                personalActionPerformed(evt);
            }
        });
        jPanel1.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, 240));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/boton.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Inicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Menú");

        mnuAlum.setText("Alumnos");
        mnuAlum.setToolTipText("");

        mnuRegAlum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuRegAlum.setText("Registro de Alumnos");
        mnuRegAlum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuRegAlumActionPerformed(evt);
            }
        });
        mnuAlum.add(mnuRegAlum);

        mnuModAlum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuModAlum.setText("Modificación de Datos de Alumnos");
        mnuAlum.add(mnuModAlum);

        HisAlum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        HisAlum.setText("Historial Clínico de Alumnos");
        mnuAlum.add(HisAlum);

        jMenu1.add(mnuAlum);

        mnuPer.setText("Personal");

        mnuRegPer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuRegPer.setText("Registro de Personal");
        mnuRegPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuRegPerActionPerformed(evt);
            }
        });
        mnuPer.add(mnuRegPer);

        mnuModPer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuModPer.setText("Modificación de Datos de Personal");
        mnuPer.add(mnuModPer);

        mnuHisPer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHisPer.setText("Historial Clínico de Personal");
        mnuPer.add(mnuHisPer);

        jMenu1.add(mnuPer);

        mnu.add(jMenu1);

        jMenu2.setText("Edit");
        mnu.add(jMenu2);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegAlumActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuRegAlumActionPerformed
    {//GEN-HEADEREND:event_mnuRegAlumActionPerformed
        new VtnRegistroAlu().setVisible(true);
    }//GEN-LAST:event_mnuRegAlumActionPerformed

    private void mnuRegPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuRegPerActionPerformed
    {//GEN-HEADEREND:event_mnuRegPerActionPerformed
        new VtnRegistroPerso().setVisible(true);
    }//GEN-LAST:event_mnuRegPerActionPerformed

    private void alumnosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_alumnosActionPerformed
    {//GEN-HEADEREND:event_alumnosActionPerformed
        new VtnAlumnos().setVisible(true);
    }//GEN-LAST:event_alumnosActionPerformed

    private void personalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_personalActionPerformed
    {//GEN-HEADEREND:event_personalActionPerformed
        new VtnPersonal().setVisible(true);
    }//GEN-LAST:event_personalActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cerrarActionPerformed
    {//GEN-HEADEREND:event_cerrarActionPerformed
        ManipulacionArchivos13.guardaArr(this, d, "Informacion.dat");
        ManipulacionArchivos13.guardaMat(this, matriz, "InformacionM.dat");
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        d = (Datos[]) ManipulacionArchivos13.cargaArr(this,"Informacion.dat");
        matriz = (HistorialClinico[][]) ManipulacionArchivos13.cargaMat(this, "InformacionM.dat");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulacionArchivos13.guardaArr(this, d, "Informacion.dat");
        ManipulacionArchivos13.guardaMat(this, matriz, "InformacionM.dat");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HisAlum;
    private javax.swing.JButton alumnos;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JMenu mnuAlum;
    private javax.swing.JMenuItem mnuHisPer;
    private javax.swing.JMenuItem mnuModAlum;
    private javax.swing.JMenuItem mnuModPer;
    private javax.swing.JMenu mnuPer;
    private javax.swing.JMenuItem mnuRegAlum;
    private javax.swing.JMenuItem mnuRegPer;
    private javax.swing.JButton personal;
    // End of variables declaration//GEN-END:variables
}
