/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import cjb.ci.Mensaje;

/**
 *
 * @author Cassandra
 */
public class VtnLogin extends javax.swing.JFrame
{

    /**
     * Creates new form VtnLoggin
     */
    public VtnLogin()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        usu = new javax.swing.JTextField();
        acceso = new javax.swing.JButton();
        con = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor Clinico Escolar");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usuActionPerformed(evt);
            }
        });
        usu.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                usuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                usuKeyTyped(evt);
            }
        });
        jPanel2.add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 290, 30));

        acceso.setText("Aceptar");
        acceso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                accesoActionPerformed(evt);
            }
        });
        jPanel2.add(acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        con.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                conKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                conKeyTyped(evt);
            }
        });
        jPanel2.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/panelLogin3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accesoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_accesoActionPerformed
    {//GEN-HEADEREND:event_accesoActionPerformed
        String usuario = "Mauro";
        String contraseña = "Sanchez";
        if (usu.getText().equals(usuario) && con.getText().equals(contraseña))
        {
            new VtnInicio().setVisible(true);
            dispose();
        } else
        {
            Mensaje.error(this, "Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_accesoActionPerformed

    private void usuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usuActionPerformed
    {//GEN-HEADEREND:event_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, con,acceso);
    }//GEN-LAST:event_formWindowOpened

    private void usuKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_usuKeyTyped
    {//GEN-HEADEREND:event_usuKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_usuKeyTyped

    private void usuKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_usuKeyPressed
    {//GEN-HEADEREND:event_usuKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, usu, con);
    }//GEN-LAST:event_usuKeyPressed

    private void conKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_conKeyPressed
    {//GEN-HEADEREND:event_conKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, con, acceso);
    }//GEN-LAST:event_conKeyPressed

    private void conKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_conKeyTyped
    {//GEN-HEADEREND:event_conKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_conKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceso;
    private javax.swing.JPasswordField con;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
