/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import proyectosp.Alumnos;
import proyectosp.Manipulacion;
import cjb.ci.Validaciones;
/**
 *
 * @author Meche}
 */
public class VtnModificaAlu extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistroAlu
     */
    public VtnModificaAlu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cve = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JCheckBox();
        sobrepeso = new javax.swing.JCheckBox();
        alergias = new javax.swing.JCheckBox();
        obecidad = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        otras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viveCon = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        carrera = new javax.swing.JComboBox<>();
        guarda = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        nom = new javax.swing.JTextArea();
        priApellido = new javax.swing.JTextArea();
        segApellido = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de Alumnos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Clave");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        cve.setEditable(false);
        cve.setColumns(20);
        cve.setRows(5);
        jPanel1.add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, 30));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel4.setText("Primer Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, 20));

        jLabel5.setText("Segundo Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 20));

        jLabel7.setText("Sexo");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 30, 20));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        sexo.setToolTipText("Seleccione el sexo del paciente.");
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 50, -1));

        desnutricion.setText("Desnutrición");
        desnutricion.setToolTipText("Marque si el paciente padece de desnitrición.");
        jPanel1.add(desnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        sobrepeso.setText("Sobrepeso");
        sobrepeso.setToolTipText("Marque si el paciente padece de sobrepeso.");
        jPanel1.add(sobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        alergias.setText("Alergias");
        alergias.setToolTipText("Marque si el paciente padece de alergias.");
        jPanel1.add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        obecidad.setText("Obecidad");
        obecidad.setToolTipText("Marque si el paciente padece de obecidad.");
        jPanel1.add(obecidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        diabetes.setText("Diabetes");
        diabetes.setToolTipText("Marque si el paciente padece de diabetes.");
        jPanel1.add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        otras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrasKeyTyped(evt);
            }
        });
        jPanel1.add(otras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 330, 190));

        jLabel6.setText("Otras");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 40, 20));

        jLabel8.setText("Vive Con");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));

        viveCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambos padres", "Solo papá", "Solo mamá", "Otro" }));
        viveCon.setToolTipText("Seleccione con quien vive el alumno(a)");
        jPanel1.add(viveCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel9.setText("Carrera");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, 20));

        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en software", "Ingenieria en plasticos", "Ingenieria en produccion industrial", "Ingenieria mecanica", "Ingenieria en computacion", "Licenciatura en seguridad ciudadana" }));
        carrera.setToolTipText("Seleccione la carrera que cursa el alumno(a)");
        jPanel1.add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        guarda.setBackground(new java.awt.Color(36, 231, 36));
        guarda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guarda.setText("Guardar");
        guarda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardaActionPerformed(evt);
            }
        });
        jPanel1.add(guarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, 30));

        cancela.setBackground(new java.awt.Color(255, 0, 0));
        cancela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancela.setText("Cancelar");
        cancela.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelaActionPerformed(evt);
            }
        });
        jPanel1.add(cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, 30));

        nom.setEditable(false);
        nom.setColumns(20);
        nom.setRows(5);
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, 30));

        priApellido.setEditable(false);
        priApellido.setColumns(20);
        priApellido.setRows(5);
        jPanel1.add(priApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, 30));

        segApellido.setEditable(false);
        segApellido.setColumns(20);
        segApellido.setRows(5);
        jPanel1.add(segApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Inicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guardaActionPerformed
    {//GEN-HEADEREND:event_guardaActionPerformed
        try
        {   
            Alumnos alum = new Alumnos(viveCon.getSelectedIndex(), carrera.getSelectedIndex(), cve.getText(), nom.getText(), priApellido.getText(), segApellido.getText(), sexo.getItemAt(sexo.getSelectedIndex()).charAt(0), desnutricion.isSelected(), sobrepeso.isSelected(), alergias.isSelected(), obecidad.isSelected(), diabetes.isSelected(), otras.getText());
            VtnInicio.d = Manipulacion.insertaMod(VtnInicio.d, alum, buscaCveMA.cv);
            Mensaje.exito(this, "Registro exitoso.");
            CtrlInterfaz.limpia(sexo, otras);
            CtrlInterfaz.habilita(false, guarda);
            desnutricion.setSelected(false);
            obecidad.setSelected(false);
            sobrepeso.setSelected(false);
            alergias.setSelected(false);
            diabetes.setSelected(false);
            dispose();
        } catch (Exception e)
        {
            Mensaje.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_guardaActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelaActionPerformed
    {//GEN-HEADEREND:event_cancelaActionPerformed
        CtrlInterfaz.limpia(sexo, otras);
        CtrlInterfaz.cambia(otras);
        CtrlInterfaz.habilita(false, guarda);
        desnutricion.setSelected(false);
        obecidad.setSelected(false);
        sobrepeso.setSelected(false);
        alergias.setSelected(false);
        diabetes.setSelected(false);
    }//GEN-LAST:event_cancelaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, guarda, nom, priApellido, segApellido, cve);
        CtrlInterfaz.cambia(otras);
        cve.setText(VtnInicio.d[buscaCveMA.cv].getCve());
        nom.setText(VtnInicio.d[buscaCveMA.cv].getNom());
        priApellido.setText(VtnInicio.d[buscaCveMA.cv].getPrimerAp());
        segApellido.setText(VtnInicio.d[buscaCveMA.cv].getSegundoAp());
    }//GEN-LAST:event_formWindowOpened

    private void otrasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyTyped
    {//GEN-HEADEREND:event_otrasKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_otrasKeyTyped

    private void otrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyPressed
    {//GEN-HEADEREND:event_otrasKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, otras, guarda);
    }//GEN-LAST:event_otrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModificaAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnModificaAlu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alergias;
    private javax.swing.JButton cancela;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JTextArea cve;
    private javax.swing.JCheckBox desnutricion;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JButton guarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea nom;
    private javax.swing.JCheckBox obecidad;
    private javax.swing.JTextField otras;
    private javax.swing.JTextArea priApellido;
    private javax.swing.JTextArea segApellido;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JCheckBox sobrepeso;
    private javax.swing.JComboBox<String> viveCon;
    // End of variables declaration//GEN-END:variables
}
