/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

/**
 *
 * @author Cassandra
 */
public class VtnPersonal extends javax.swing.JFrame
{

    /**
     * Creates new form VtnPrin
     */
    public VtnPersonal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RegistroHCPer = new javax.swing.JButton();
        ModificaPer = new javax.swing.JButton();
        ConsultaPer = new javax.swing.JButton();
        RegistroPer = new javax.swing.JButton();
        ReportesPer = new javax.swing.JButton();
        ConsultaHP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de Personal");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroHCPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Registro-HC.png"))); // NOI18N
        RegistroHCPer.setToolTipText("Registro de historial clinico");
        RegistroHCPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegistroHCPerActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroHCPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        ModificaPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/ModificacionPersonal.png"))); // NOI18N
        ModificaPer.setToolTipText("Modificaciones de alumnos o profesores");
        ModificaPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificaPerActionPerformed(evt);
            }
        });
        jPanel1.add(ModificaPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        ConsultaPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/ConsultaPersonal.png"))); // NOI18N
        ConsultaPer.setToolTipText("Consulta de alumnos o profesores");
        ConsultaPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConsultaPerActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultaPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        RegistroPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/RegistroPersonal.png"))); // NOI18N
        RegistroPer.setToolTipText("Registro de alumnos o profesores");
        RegistroPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegistroPerActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        ReportesPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Reportes.png"))); // NOI18N
        ReportesPer.setToolTipText("Reportes");
        ReportesPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ReportesPerActionPerformed(evt);
            }
        });
        jPanel1.add(ReportesPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        ConsultaHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/busqueda-de-datos.png"))); // NOI18N
        ConsultaHP.setToolTipText("Consulta de alumnos o profesores");
        ConsultaHP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConsultaHPActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultaHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 210, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Inicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistroPerActionPerformed
    {//GEN-HEADEREND:event_RegistroPerActionPerformed
        new VtnRegistroPerso().setVisible(true);
    }//GEN-LAST:event_RegistroPerActionPerformed

    private void ConsultaPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConsultaPerActionPerformed
    {//GEN-HEADEREND:event_ConsultaPerActionPerformed
        new VtnConsultaPer().setVisible(true);
    }//GEN-LAST:event_ConsultaPerActionPerformed

    private void ModificaPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificaPerActionPerformed
    {//GEN-HEADEREND:event_ModificaPerActionPerformed
        new buscaCveMP().setVisible(true);
    }//GEN-LAST:event_ModificaPerActionPerformed

    private void RegistroHCPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistroHCPerActionPerformed
    {//GEN-HEADEREND:event_RegistroHCPerActionPerformed
        new buscaCveRHP().setVisible(true);
    }//GEN-LAST:event_RegistroHCPerActionPerformed

    private void ConsultaHPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConsultaHPActionPerformed
    {//GEN-HEADEREND:event_ConsultaHPActionPerformed
        new VtnConsultaHP().setVisible(true);
    }//GEN-LAST:event_ConsultaHPActionPerformed

    private void ReportesPerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ReportesPerActionPerformed
    {//GEN-HEADEREND:event_ReportesPerActionPerformed
        new VtnReportesP().setVisible(true);
    }//GEN-LAST:event_ReportesPerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaHP;
    private javax.swing.JButton ConsultaPer;
    private javax.swing.JButton ModificaPer;
    private javax.swing.JButton RegistroHCPer;
    private javax.swing.JButton RegistroPer;
    private javax.swing.JButton ReportesPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
