/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import proyectosp.Manipulacion;
import proyectosp.Personal;

/**
 *
 * @author Meche}
 */
public class VtnRegistroPerso extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistroAlu
     */
    public VtnRegistroPerso()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cve = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        primerAp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        segundoAp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JCheckBox();
        sobrepeso = new javax.swing.JCheckBox();
        alergias = new javax.swing.JCheckBox();
        obecidad = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        otras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        estatus = new javax.swing.JComboBox<>();
        cancela = new javax.swing.JButton();
        guarda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Personal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Clave");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 20));

        cve.setToolTipText("Acepta los digitos de la matricula del personal.");
        cve.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveKeyTyped(evt);
            }
        });
        jPanel1.add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        nom.setToolTipText("Ingresa el nombre(s) del personal.");
        nom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));

        jLabel4.setText("Primer Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 90, 20));

        primerAp.setToolTipText("Ingresa el apellido paterno del personal.");
        primerAp.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                primerApKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                primerApKeyTyped(evt);
            }
        });
        jPanel1.add(primerAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 110, -1));

        jLabel5.setText("Segundo Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 20));

        segundoAp.setToolTipText("Ingresa el apellido materno del personal.");
        segundoAp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                segundoApActionPerformed(evt);
            }
        });
        segundoAp.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                segundoApKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                segundoApKeyTyped(evt);
            }
        });
        jPanel1.add(segundoAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 110, -1));

        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 20));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        sexo.setToolTipText("Seleccione el sexo del paciente.");
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 50, -1));

        desnutricion.setText("Desnutrición");
        desnutricion.setToolTipText("Marque si el paciente padece de desnitrición.");
        jPanel1.add(desnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        sobrepeso.setText("Sobrepeso");
        sobrepeso.setToolTipText("Marque si el paciente padece de sobrepeso.");
        jPanel1.add(sobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        alergias.setText("Alergias");
        alergias.setToolTipText("Marque si el paciente padece de alergias.");
        jPanel1.add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        obecidad.setText("Obecidad");
        obecidad.setToolTipText("Marque si el paciente padece de obecidad.");
        jPanel1.add(obecidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        diabetes.setText("Diabetes");
        diabetes.setToolTipText("Marque si el paciente padece de diabetes.");
        jPanel1.add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel6.setText("Otras");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 40, 20));

        otras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrasKeyTyped(evt);
            }
        });
        jPanel1.add(otras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 330, 190));

        jLabel8.setText("Estatus");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base", "Temporal" }));
        estatus.setToolTipText("Seleccione el estatus de permanencia del paciente.");
        jPanel1.add(estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 70, -1));

        cancela.setBackground(new java.awt.Color(255, 0, 0));
        cancela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancela.setText("Cancelar");
        cancela.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelaActionPerformed(evt);
            }
        });
        jPanel1.add(cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, 30));

        guarda.setBackground(new java.awt.Color(36, 231, 36));
        guarda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guarda.setText("Guardar");
        guarda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardaActionPerformed(evt);
            }
        });
        jPanel1.add(guarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/Inicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guardaActionPerformed
    {//GEN-HEADEREND:event_guardaActionPerformed
        try
        {
            if (!Manipulacion.validarCveAlumnosVtn(VtnInicio.d, cve.getText()))
            {
                Mensaje.error(this, "La clave que intenta ingresar ya esta registrada...");
                CtrlInterfaz.limpia(cve,nom,primerAp,segundoAp,otras);
                desnutricion.setSelected(false);
                obecidad.setSelected(false);
                sobrepeso.setSelected(false);
                alergias.setSelected(false);
                diabetes.setSelected(false);
                CtrlInterfaz.cambia(cve);
                CtrlInterfaz.habilita(false, nom, primerAp, segundoAp, otras, guarda);
            } else
            {
                Personal per = new Personal(estatus.getItemAt(estatus.getSelectedIndex()).charAt(0), cve.getText(), nom.getText(), primerAp.getText(), segundoAp.getText(), sexo.getItemAt(sexo.getSelectedIndex()).charAt(0), desnutricion.isSelected(), sobrepeso.isSelected(), alergias.isSelected(), obecidad.isSelected(), diabetes.isSelected(), otras.getText());
                VtnInicio.d = Manipulacion.inserta(VtnInicio.d, per);
                VtnInicio.matriz = Manipulacion.crearMatriz(VtnInicio.matriz, VtnInicio.d);
                Mensaje.exito(this, "Registro exitoso.");
                CtrlInterfaz.limpia(cve, nom, primerAp, segundoAp, sexo, otras);
                CtrlInterfaz.habilita(false, nom, primerAp, segundoAp, otras, guarda);
                desnutricion.setSelected(false);
                obecidad.setSelected(false);
                sobrepeso.setSelected(false);
                alergias.setSelected(false);
                diabetes.setSelected(false);
            }
        } catch (Exception e)
        {
            Mensaje.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_guardaActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelaActionPerformed
    {//GEN-HEADEREND:event_cancelaActionPerformed
        CtrlInterfaz.limpia(cve, nom, primerAp, segundoAp, sexo, otras);
        desnutricion.setSelected(false);
        obecidad.setSelected(false);
        sobrepeso.setSelected(false);
        alergias.setSelected(false);
        diabetes.setSelected(false);
        CtrlInterfaz.habilita(false, nom, primerAp, segundoAp, otras, guarda);
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_cancelaActionPerformed

    private void cveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyTyped
    {//GEN-HEADEREND:event_cveKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_cveKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt);    
    }//GEN-LAST:event_nomKeyTyped

    private void primerApKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerApKeyTyped
    {//GEN-HEADEREND:event_primerApKeyTyped
        Validaciones.validaAlfabeticos(evt); 
    }//GEN-LAST:event_primerApKeyTyped

    private void segundoApActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_segundoApActionPerformed
    {//GEN-HEADEREND:event_segundoApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoApActionPerformed

    private void segundoApKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoApKeyTyped
    {//GEN-HEADEREND:event_segundoApKeyTyped
        Validaciones.validaAlfabeticos(evt);      
    }//GEN-LAST:event_segundoApKeyTyped

    private void otrasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyTyped
    {//GEN-HEADEREND:event_otrasKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_otrasKeyTyped

    private void cveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyPressed
    {//GEN-HEADEREND:event_cveKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, cve, nom);            
    }//GEN-LAST:event_cveKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, nom, primerAp, segundoAp, otras, guarda);
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_formWindowOpened

    private void primerApKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerApKeyPressed
    {//GEN-HEADEREND:event_primerApKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, primerAp, segundoAp);        
    }//GEN-LAST:event_primerApKeyPressed

    private void segundoApKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoApKeyPressed
    {//GEN-HEADEREND:event_segundoApKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, segundoAp, otras);               
    }//GEN-LAST:event_segundoApKeyPressed

    private void otrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyPressed
    {//GEN-HEADEREND:event_otrasKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, otras, guarda);    
    }//GEN-LAST:event_otrasKeyPressed

    private void nomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomActionPerformed
    {//GEN-HEADEREND:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, primerAp);        
    }//GEN-LAST:event_nomKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistroPerso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alergias;
    private javax.swing.JButton cancela;
    private javax.swing.JTextField cve;
    private javax.swing.JCheckBox desnutricion;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JComboBox<String> estatus;
    private javax.swing.JButton guarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nom;
    private javax.swing.JCheckBox obecidad;
    private javax.swing.JTextField otras;
    private javax.swing.JTextField primerAp;
    private javax.swing.JTextField segundoAp;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JCheckBox sobrepeso;
    // End of variables declaration//GEN-END:variables
}
