/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtngestor;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectosp.Alumnos;
import proyectosp.Datos;
import proyectosp.Personal;

/**
 *
 * @author chemo
 */
public class VtnReportesP extends javax.swing.JFrame
{

    DefaultTableModel dtm;

    /**
     * Creates new form VtnReportesA
     */
    public VtnReportesP()
    {
        initComponents();
        String com[] =
        {
            "Clave", "Nombre", "Primer Apellido", "Segundo Apellido", "Sexo", "Desnutricion", "Sobrepeso", "Alergias","Obecidad", "Diabetes", "Otros", "Estatus"
        };
        dtm = new DefaultTableModel(com, 0);
        desp.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desp = new javax.swing.JTable();
        checkHombres = new javax.swing.JCheckBox();
        checkMujeres = new javax.swing.JCheckBox();
        checkAlergias = new javax.swing.JCheckBox();
        checkSobrepeso = new javax.swing.JCheckBox();
        checkDiabetes = new javax.swing.JCheckBox();
        checkDesnutricion = new javax.swing.JCheckBox();
        checkObesidad = new javax.swing.JCheckBox();
        checkOtros = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setEnabled(false);

        desp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        desp.setEnabled(false);
        jScrollPane1.setViewportView(desp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1180, 430));

        checkHombres.setText("Hombres");
        jPanel1.add(checkHombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        checkMujeres.setText("Mujeres");
        checkMujeres.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkMujeresActionPerformed(evt);
            }
        });
        jPanel1.add(checkMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        checkAlergias.setText("Alergias");
        jPanel1.add(checkAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        checkSobrepeso.setText("Sobrepeso");
        jPanel1.add(checkSobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        checkDiabetes.setText("Diabetes");
        jPanel1.add(checkDiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        checkDesnutricion.setText("Desnutricion");
        jPanel1.add(checkDesnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        checkObesidad.setText("Obesidad");
        jPanel1.add(checkObesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));

        checkOtros.setText("Otros");
        checkOtros.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkOtrosActionPerformed(evt);
            }
        });
        jPanel1.add(checkOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, -1, -1));

        aceptar.setBackground(new java.awt.Color(36, 229, 36));
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, -1, 30));

        jLabel2.setText("Filtro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vtngestor/imagenes/cve222.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1180, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) desp.getModel();
        model.setColumnIdentifiers(new Object[]{"Clave", "Nombre", "Primer Apellido", "Segundo Apellido", "Sexo", "Desnutricion", "Sobrepeso", "Alergias","Obecidad", "Diabetes", "Otros", "Estatus"});
        
        JTableHeader header = desp.getTableHeader();
        header.setReorderingAllowed(false);
        
        JTableHeader header1 = desp.getTableHeader();
        header.setResizingAllowed(false);
    }//GEN-LAST:event_formWindowOpened

    private void checkMujeresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkMujeresActionPerformed
    {//GEN-HEADEREND:event_checkMujeresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMujeresActionPerformed

    private void checkOtrosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkOtrosActionPerformed
    {//GEN-HEADEREND:event_checkOtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOtrosActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        limpiarTabla();
        filtro();
    }//GEN-LAST:event_aceptarActionPerformed
    public void filtro()
    {
        for (int i = 0; i < VtnInicio.d.length; i++)
        {
            if (cumpleCondiciones(VtnInicio.d[i]))
            {
                if (VtnInicio.d[i] instanceof Personal)
                {
                    Personal personal = (Personal) VtnInicio.d[i];
                    Object[] rowData = obtenerDatosPersonal(personal);
                    dtm.addRow(rowData);
                }
            }
        }
    }

    private boolean cumpleCondiciones(Datos dato)
    {
        return (cumpleCondicion(checkDiabetes.isSelected(), dato.isDiabetes())
                && cumpleCondicion(checkMujeres.isSelected(), dato.getSexo() == 'F')
                && cumpleCondicion(checkHombres.isSelected(), dato.getSexo() == 'M')
                && cumpleCondicion(checkAlergias.isSelected(), dato.isAlergias())
                && cumpleCondicion(checkSobrepeso.isSelected(), dato.isSobrepeso())
                && cumpleCondicion(checkDesnutricion.isSelected(), dato.isDesnutricion())
                && cumpleCondicion(checkObesidad.isSelected(), dato.isObecidad())
                && cumpleCondicion(checkOtros.isSelected(), dato.getOtras() != null));
    }

    private boolean cumpleCondicion(boolean checkboxSeleccionado, boolean condicionDato)
    {
        return checkboxSeleccionado == condicionDato || !checkboxSeleccionado;
    }

    private Object[] obtenerDatosPersonal(Personal personal)
    {
        return new Object[]
        {
            personal.getCve(),
            personal.getNom(),
            personal.getPrimerAp(),
            personal.getSegundoAp(),
            personal.getSexo(),
            convertirBooleanoASiNo(personal.isDesnutricion()),
            convertirBooleanoASiNo(personal.isSobrepeso()),
            convertirBooleanoASiNo(personal.isAlergias()),
            convertirBooleanoASiNo(personal.isObecidad()),
            convertirBooleanoASiNo(personal.isDiabetes()),
            personal.getOtras(),
            obtenerEstatus(personal.getEstatus()),
        };
    }
    
    private String obtenerEstatus(int opcion)
    {
        String s="";
                
        switch (opcion)
        {
            case 'B':
                return "Base";
            case 'T':
                return "Temporal";
        }
        return s;
    }
    
    private String convertirBooleanoASiNo(boolean valor)
    {
        return valor ? "Si" : "No";
    }
    
    private void limpiarTabla()
    {
        DefaultTableModel dtm = (DefaultTableModel) desp.getModel();
        dtm.setRowCount(0); 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnReportesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnReportesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnReportesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnReportesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnReportesP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox checkAlergias;
    private javax.swing.JCheckBox checkDesnutricion;
    private javax.swing.JCheckBox checkDiabetes;
    private javax.swing.JCheckBox checkHombres;
    private javax.swing.JCheckBox checkMujeres;
    private javax.swing.JCheckBox checkObesidad;
    private javax.swing.JCheckBox checkOtros;
    private javax.swing.JCheckBox checkSobrepeso;
    private javax.swing.JTable desp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
